# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'json', '~> 2.7'
gem 'puma', '~> 6.4'
gem 'sinatra', '~> 4.0'

group :development do
  gem 'rack-test', '~> 2.1'
  gem 'rspec', '~> 3.13'
end
